
from mongoengine import *

connect('ais', host='114.242.60.27', authentication_source='admin', username='admin', password='123456', port=6701)


class Ships(Document):
    location = PointField()  # geo地理信息
    MMSI = IntField()
    IMO = IntField()
    ShipName = StringField()
    CallSign = StringField()
    ShipTypeCN = StringField()
    ShipTypeEN = StringField()
    NavStatusCN = StringField()
    NavStatusEN = StringField()
    Length = FloatField()
    Width = FloatField()
    Draught = FloatField()
    Heading = FloatField()
    Course = FloatField()
    Speed = FloatField()
    Lon = StringField()
    Lat = StringField()
    Rot = FloatField()
    Dest = StringField()
    ETA = StringField()
    Receivedtime = StringField()
    UnixTime = IntField()
    Lon_d = FloatField()
    Lat_d = FloatField()
    AisType = StringField()

    meta = {  # 按所列属性建立索引
        'indexes': ['ShipName', 'location', 'MMSI'],
        'collection': 'ships', 'strict': False
    }


class ShipInfo(Document):
    imo = StringField()
    shipname = StringField()
    shipallname = StringField()
    mmsi = StringField()
    portofregistry = StringField()
    pandiclub = StringField()
    shipstatus = StringField()
    shipstatuseffectivedate = StringField()
    builddate = StringField()
    buildcountry = StringField()
    statcode5 = StringField()
    shiptypegroup = StringField()
    shiptypelevel5subgroup = StringField()
    shiptypecode = StringField()
    shiptype = StringField()
    flagcode = StringField()
    flagcountry = StringField()
    flageffectivedate = StringField()
    classname = StringField()
    classnarrative = StringField()
    doccompanycode = StringField()
    doccompany = StringField()
    doccompanycountry = StringField()
    groupcompanycode = StringField()
    groupcompany = StringField()
    groupcompanycountry = StringField()
    operatorcompanycode = StringField()
    operatorcompany = StringField()
    operatorcompanycountry = StringField()
    registeredownercode = StringField()
    registeredowner = StringField()
    registeredownercountry = StringField()
    shipmanagercompanycode = StringField()
    shipmanagercompany = StringField()
    shipmanagercompanycountry = StringField()
    technicalmanagercode = StringField()
    technicalmanager = StringField()
    technicalmanagercountry = StringField()
    shipbuildercompanycode = StringField()
    shipbuildercompany = StringField()
    shipbuildercompanycountry = StringField()
    deadweight = StringField()
    grosstonnage = StringField()
    length = StringField()
    lengthloa = StringField()
    lengthregistered = StringField()
    maxwidth = StringField()
    mouldwidth = StringField()
    depth = StringField()
    teu = StringField()
    speedmax = StringField()
    speedservice = StringField()
    nettonnage = StringField()
    draught = StringField()
    tpcmi = StringField()
    displacement = StringField()
    lightdisplacement = StringField()
    bunkersdescriptive = StringField()
    fueltype1 = StringField()
    fueltype1capacity = StringField()
    fueltype2capacity = StringField()
    fueltype2 = StringField()
    callsign = StringField()
    launchdate = StringField()
    sistershipimo = StringField()
    gascapacity = StringField()
    graincapacity = StringField()
    liquidcapacity = StringField()
    numberrefrigeratedcontainers = StringField()
    numberofteu = StringField()
    maxswlofgear = StringField()
    standardshipdesign = StringField()
    mainenginedesigner = StringField()
    mainenginebuildercode = StringField()
    mainenginebuilder = StringField()
    mainenginemodel = StringField()
    mainnumberofcylinders = StringField()
    mainstroketype = StringField()
    mainpowerbhp = StringField()
    mainpowerkw = StringField()
    mainrpm = StringField()
    fuelconsumptiontotal = StringField()
    fuelconsumptionmainenginesonly = StringField()
    auxilarygeneratorsdescriptive = StringField()
    countryofeconomicbenefit = StringField()
    dataupdatetime = StringField()
    meta = {  # 按所列属性建立索引
        'indexes': ['shipname', 'mmsi'],
        'collection': 'shipinfo', 'strict': False
    }


class ShipTrajectory(Document):
    mmsi = StringField()
    course = ListField()
    location = ListField()
    meta = {  # 按所列属性建立索引
        'indexes': ['location', 'mmsi'],
        'collection': 'shiptrajectory', 'strict': False
    }
